name: Génération du serpent arc-en-ciel

on:
  schedule:
    - cron: "0 */6 * * *"   # toutes les 6 heures
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Générer le SVG du serpent (palette arc-en-ciel)
        uses: Platane/snk@v3
        with:
          github_user_name: mikaelkabore768-commits
          outputs: |
            dist/github-contribution-grid-snake-rainbow.svg?color_snake=%23FF00FF,%2300BFFF,%2300FF7F,%23FFFF00,%23FF7F00&color_dots=%23222,%23FF7F00,%23FFFF00,%2300FF7F,%2300BFFF,%23FF00FF

      - name: Publier sur la branche output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
